spring:
  application:
    name: card-transfer-backend

server:
  port: 5500

logging:
  level:
    root: INFO
    com.yourpackage: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 100MB
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
